yeezyName: '&e&lYeezys'
yeezyDescription: '&5Abgenutzt will diese Schuhe keiner anziehen!'
villagerTokenName: '&bDorfbewohner-Token'
villagerTokenDescription: '&fKlicke auf einen Dorfbewohner./n&fSch端tzt nur vor dem MobRemover./n&fAchtung, der Dorfbewohner kann trotzdem/n&fsterben!'
antiqueArmorName: '&e&lAntike R端stung'
antiqueArmorDescription: '&5Nur wahre Krieger tragen diese R端stung!'
antiqueSwordName: '&e&lAntikes Schwert'
antiqueSwordDescription: '&fDieses Schwert ist antik. Es ist 端ber &c1.000 Jahre &falt.'
colaName: '&5Cola'
colaDescription: '&fGibt dir einen Energieschub!'