yeezyName: '&6&lYeezys'
yeezyDescription: '&5Abgenutzt will diese Schuhe keiner anziehen!'
antiqueArmorName: '&6&lAntike Rüstung'
antiqueArmorDescription: '&5Nur wahre Krieger tragen diese Rüstung!'
antiqueSwordName: '&6&lAntikes Schwert'
antiqueSwordDescription: '&fDieses Schwert ist antik. Es ist über &c1.000 Jahre &falt.'
colaName: '&5Cola'
colaDescription: '&fGibt dir einen Energieschub!'